name: Windows RDP via Ngrok

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup and Start Ngrok RDP Tunnel
      run: |
        Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath $env:USERPROFILE\ngrok
        cd $env:USERPROFILE\ngrok
        .\ngrok.exe authtoken 30VJ0Myc22G6MwzSLG8mrmcfHJ2_6QtyHGsxuvCez58BnNsRJ

        # Start ngrok and log output to file
        Start-Process -NoNewWindow -FilePath .\ngrok.exe -ArgumentList @("tcp", "3389", "--log", "ngrok.log")
        Start-Sleep -Seconds 15

        # Output the ngrok RDP link
        Get-Content ngrok.log | Select-String "tcp://"
